apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wbstack-com-tls
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: wbstack-com-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: '*.wbstack.com'
  dnsNames:
    - wbstack.com
    - '*.wbstack.com'
  acme:
    config:
      - dns01:
          provider: clouddns
        domains:
          - wbstack.com
          - '*.wbstack.com'
