releases:
- name: tool-widar
  namespace: default
  chart: ./../../../charts/tool-widar
  values:
    - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../../private/helm/default.yaml
