releases:
- name: mediawiki-134
  namespace: default
  chart: ./../../../charts/mediawiki
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../../private/helm/default.yaml
