repositories:
- name: stable
  url: https://charts.helm.sh/stable

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  wbstack:
    kubeContext: gke_wbstack_us-east1-b_cluster-1

releases:
  - name: nginx-ingress
    namespace: kube-system
    chart: stable/nginx-ingress
    version: 1.34.3
    values:
    - "values.yaml"
