image:
  repository: ghcr.io/wbstack/ui
  tag: "2.3"
  pullPolicy: Always
resources:
  requests:
    cpu: 1m
    memory: 6Mi
  limits:
    cpu: 10m
    memory: 20Mi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
  hosts:
  - host: www.wbstack.com
    paths:
    - /*
  tls:
  - hosts:
    - www.wbstack.com
    secretName: wbstack-com-tls-prod
