resources:
  requests:
    cpu: 0.2
    memory: "3500Mi"
  limits:
    cpu: 0.5
    memory: "4072Mi"
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: faster
  size: 12Gi
  annotations: {}
