repositories:
- name: wbstack
  url: https://wbstack.github.io/charts

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  wbstack:
    kubeContext: gke_wbstack_us-east1-b_cluster-1

releases:
- name: queryservice-updater
  namespace: default
  chart: wbstack/queryservice-updater
  version: 0.1.0
  values:
  - "values.yaml"
