repositories:
- name: wbstack
  url: https://wbstack.github.io/charts

releases:
- name: queryservice-updater
  namespace: default
  chart: wbstack/queryservice-updater
  version: 0.1.0
  values:
  - "values.yaml"
