replicaCount: 1
image:
  repository: ghcr.io/wbstack/queryservice-updater
  tag: 0.3.6_2.1
  pullPolicy: Always
app:
  sleepTime: 5
  loopLimit: 100
  getBatchesEndpoint: http://api-app-backend.default.svc.cluster.local/backend/qs/getBatches
resources:
  requests:
    cpu: 40m
    memory: 80Mi
  limits:
    cpu: 70m
    memory: 120Mi
