replicaCount: 1
image:
  repository: ghcr.io/wbstack/queryservice-updater
  tag: 0.3.6_2.1
  pullPolicy: Always
app:
  sleepTime: 5
  getBatchesEndpoint: http://api-app-backend.default.svc.cluster.local/backend/qs/getBatches
resources:
  requests:
    cpu: 30m
    memory: 65Mi
  limits:
    cpu: 60m
    memory: 100Mi
