repositories:
  - name: cetic
    url: https://cetic.github.io/helm-charts

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  wbstack:
    kubeContext: gke_wbstack_us-east1-b_cluster-1
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml

releases:
  - name: adminer
    namespace: default
    chart: cetic/adminer
    version: v0.1.6
    values:
      - "values.yaml.gotmpl"
