repositories:
- name: jetstack
  url: https://charts.jetstack.io

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  wbstack:
    kubeContext: gke_wbstack_us-east1-b_cluster-1

releases:
- name: cert-manager
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: v1.2.0
  values:
  - "values.yaml"
