repositories:
- name: wbstack
  url: https://wbstack.github.io/charts

releases:
- name: clusterissuers
  namespace: cert-manager
  chart: wbstack/wbstack-clusterissuers
  version: 0.1.0
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml
