repositories:
- name: wbstack
  url: https://wbstack.github.io/charts

releases:
- name: mediawiki-135
  namespace: default
  chart: wbstack/mediawiki
  version: 0.1.0
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml
