# Permit co-located instances for solitary minikube virtual machines.
antiAffinity: "soft"

# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "standard"
  resources:
    requests:
      storage: 1000M