repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
- name: redis
  namespace: default
  chart: bitnami/redis
  version: 13.0.1
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../../private/helm/default.yaml
