apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wbstack-com-tls-staging
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: wbstack-com-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.wbstack.com'
  dnsNames:
    - wbstack.com
    - '*.wbstack.com'
  acme:
    config:
      - dns01:
          provider: clouddns
        domains:
          - wbstack.com
          - '*.wbstack.com'
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: opencura-com-tls-staging
  namespace: default
  labels:
    app.kubernetes.io/managed-by: ManualGit
spec:
  secretName: opencura-com-tls-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: '*.opencura.com'
  dnsNames:
    - '*.opencura.com'
    - '*.wiki.opencura.com'
    - '*.wikibase.opencura.com'
    - '*.test.opencura.com'
  acme:
    config:
      - dns01:
          provider: clouddns
        domains:
          - '*.opencura.com'
          - '*.wiki.opencura.com'
          - '*.wikibase.opencura.com'
          - '*.test.opencura.com'
