repositories:
  - name: wbstack-charts-api
    url: git+https://github.com/wbstack/charts/@api?ref=main
releases:
- name: api
  namespace: default
  chart: wbstack-charts-api/api
  set:
  - name: app.passport.public
    file: ./../../../../private/private/apps/api/oauth-public.key
  - name: app.passport.private
    file: ./../../../../private/private/apps/api/oauth-private.key
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../../../../private/private/helm/default.yaml
