repositories:
- name: wbstack
  url: https://wbstack.github.io/charts

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  wbstack:
    kubeContext: gke_wbstack_us-east1-b_cluster-1
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml

releases:
- name: api
  namespace: default
  chart: wbstack/api
  version: 0.2.0
  set:
  - name: app.passport.public
    file: ./../../../../private/apps/api/oauth-public.key
  - name: app.passport.private
    file: ./../../../../private/apps/api/oauth-private.key
  values:
  - "values.yaml.gotmpl"
