releases:
- name: api
  namespace: default
  chart: ./../../../charts/api
  set:
  - name: app.passport.public
    file: ./../../../../private/apps/api/oauth-public.key
  - name: app.passport.private
    file: ./../../../../private/apps/api/oauth-private.key
  values:
  - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml
