repositories:
 - name: elastic
   url: https://helm.elastic.co

environments:
  default:
    kubeContext: INVALID-ENVIRONMENT
  wbstack:
    kubeContext: gke_wbstack_us-east1-b_cluster-1

releases:
- name: elasticsearch
  namespace: default
  chart: elastic/elasticsearch
  version: 6.8.17
  values:
  - "values.yaml"