repositories:
- name: wbstack
  url: https://wbstack.github.io/charts

releases:
- name: tool-quickstatements
  namespace: default
  chart: wbstack/tool-quickstatements
  version: 0.1.0
  values:
    - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml
