releases:
- name: tool-quickstatements
  namespace: default
  chart: ./../../../charts/tool-quickstatements
  values:
    - "values.yaml.gotmpl"

environments:
  default:
    values:
      - ./../default.yaml
      - ./../../../../private/helm/private.yaml
